### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by jessrod11** [jessrod11/Language-Translator#7]
# Story
 “ As a user, in order to type on the page and eventually translate the text, I need to create a text area and three buttons" 

# Acceptance Criteria
**When** the page loads
**Then**- there should be a text area and three language buttons and an output area.

# Technical Notes
 - text area tag ```<text area>```
 - button tags with id's for each language. ```<button id="spanish></button>```
 - div with an id for output area ```<div id=output-container>```
![screen shot 2018-03-08 at 7 16 27 pm](https://user-images.githubusercontent.com/22329231/37188376-5c83f3f6-2314-11e8-8001-76d83a637845.png)

**Comment by Ian-Boraks** [comment]
Do you need the 3  language buttons to do anything or do you just want base code that you can edit off of (as a starting point)?

**Comment by jessrod11** [comment]
Hey @Cutwow ! I don't want the buttons to do anything on this ticket. This is just basic HTML. I've created another ticket where I will target the buttons and make them do something. :)
